// SPDX-License-Identifier: AGPL-3.0-or-later
//
// Generates the browser's protobuf types from `proto/` and bundles the network
// module the panels import.
//
// **The bundle is committed**, for the same reason `daemon/src/triald/_proto/`
// is: a checkout runs with uv alone. The panels are copied into the wheel by
// `packaging/Makefile`, so a bundle produced at package time would make npm a
// build dependency of every release — and of every rig that builds one. It is
// not. `npm ci` installs exactly what package-lock.json pins, so the bundle is
// reproducible; `make check-web` is what holds it to the proto.
//
// Only this one file is bundled. The panels stay hand-written ES modules served
// as themselves, so editing `elements/*.js` and reloading the page still works.

import { execFileSync } from "node:child_process";
import { mkdirSync, rmSync, readFileSync, writeFileSync, readdirSync } from "node:fs";
import { dirname, join } from "node:path";
import { fileURLToPath } from "node:url";

import * as esbuild from "esbuild";

const here = dirname(fileURLToPath(import.meta.url));
const protoRoot = join(here, "../../proto");
const generated = join(here, "gen");
const bundle = join(here, "elements/daemon_api_client.js");

rmSync(generated, { recursive: true, force: true });
mkdirSync(generated, { recursive: true });

// Every file in both packages, found rather than listed: a proto added to the
// interface is part of the interface, and a list here is a way to leave one
// out. `braemons/v1/` is what the family agrees on — today the `.tdr` outcome
// taxonomy, which statemachined speaks too and neither daemon owns.
const protoFiles = ["triald/v1", "braemons/v1"].flatMap((directory) =>
  readdirSync(join(protoRoot, directory))
    .filter((name) => name.endsWith(".proto"))
    .sort()
    .map((name) => `${protoRoot}/${directory}/${name}`),
);

execFileSync(
  "protoc",
  [
    `--proto_path=${protoRoot}`,
    `--plugin=protoc-gen-es=${join(here, "node_modules/.bin/protoc-gen-es")}`,
    `--es_out=${generated}`,
    "--es_opt=target=js,import_extension=js",
    ...protoFiles,
  ],
  { stdio: "inherit" },
);

await esbuild.build({
  entryPoints: [join(here, "src/daemon_api_client.js")],
  outfile: bundle,
  bundle: true,
  format: "esm",
  platform: "browser",
  target: "es2022",
  // Not minified, deliberately. A committed artifact nobody can read is a
  // committed artifact nobody reviews, and `make check-web` diffs this file.
  minify: false,
  legalComments: "none",
});

// The banner goes on afterwards so esbuild's own output is the only thing the
// staleness check compares, and so the first line of the file says what it is.
const banner = `// SPDX-License-Identifier: AGPL-3.0-or-later
//
// @generated by client/web/build_daemon_api_client.mjs — run \`make web\`, do not edit.
//
// The source is client/web/src/daemon_api_client.js; the protobuf types are
// generated from proto/triald/v1/; the rest is @bufbuild/protobuf and
// @connectrpc/connect-web, bundled so that a checkout needs no npm to run.
`;
writeFileSync(bundle, banner + readFileSync(bundle, "utf8"));

console.log(`elements/daemon_api_client.js — ${(readFileSync(bundle).length / 1024).toFixed(0)} KiB`);
