# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: triald/v1/common.proto
"""Generated protocol buffer code."""
from google.protobuf.internal import builder as _builder
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x16triald/v1/common.proto\x12\ttriald.v1\"&\n\x05\x45rror\x12\r\n\x05\x65rror\x18\x01 \x01(\t\x12\x0e\n\x06\x64\x65tail\x18\x02 \x01(\t\"\x10\n\x02Ok\x12\n\n\x02ok\x18\x01 \x01(\x08*t\n\x0cManipulandum\x12\x08\n\x04NONE\x10\x00\x12\t\n\x05LEVER\x10\x01\x12\r\n\tTOUCH_BAR\x10\x02\x12\n\n\x06\x42UTTON\x10\x03\x12\x0c\n\x08JOYSTICK\x10\x04\x12\x0b\n\x07GAMEPAD\x10\x05\x12\n\n\x06SERIAL\x10\x06\x12\r\n\tSIMULATED\x10\x07*\xad\x01\n\x13TrialCountCriterion\x12%\n!TRIAL_COUNT_CRITERION_UNSPECIFIED\x10\x00\x12)\n%TRIAL_COUNT_CRITERION_ACCEPTED_TRIALS\x10\x01\x12\x1e\n\x1aTRIAL_COUNT_CRITERION_HITS\x10\x02\x12$\n TRIAL_COUNT_CRITERION_ALL_TRIALS\x10\x03*\xbc\x01\n\x08Ordering\x12\x18\n\x14ORDERING_UNSPECIFIED\x10\x00\x12\x1c\n\x18ORDERING_RANDOM_IN_ROUND\x10\x01\x12!\n\x1dORDERING_RANDOM_IN_EXPERIMENT\x10\x02\x12\x16\n\x12ORDERING_ASCENDING\x10\x03\x12\x17\n\x13ORDERING_DESCENDING\x10\x04\x12$\n ORDERING_RANDOM_WITH_REPLACEMENT\x10\x05\x62\x06proto3')

_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, globals())
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'triald.v1.common_pb2', globals())
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  _MANIPULANDUM._serialized_start=95
  _MANIPULANDUM._serialized_end=211
  _TRIALCOUNTCRITERION._serialized_start=214
  _TRIALCOUNTCRITERION._serialized_end=387
  _ORDERING._serialized_start=390
  _ORDERING._serialized_end=578
  _ERROR._serialized_start=37
  _ERROR._serialized_end=75
  _OK._serialized_start=77
  _OK._serialized_end=93
# @@protoc_insertion_point(module_scope)
