# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: triald/v1/debug.proto
"""Generated protocol buffer code."""
from google.protobuf.internal import builder as _builder
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from triald.v1 import session_pb2 as triald_dot_v1_dot_session__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x15triald/v1/debug.proto\x12\ttriald.v1\x1a\x17triald/v1/session.proto\"\x8e\x03\n\x0bSimSettings\x12\x1a\n\x08hit_rate\x18\x01 \x01(\x01R\x08hit_rate\x12*\n\x10not_started_rate\x18\x02 \x01(\x01R\x10not_started_rate\x12&\n\x0e\x65ye_error_rate\x18\x03 \x01(\x01R\x0e\x65ye_error_rate\x12\x1e\n\nearly_rate\x18\x04 \x01(\x01R\nearly_rate\x12(\n\x0f\x66rame_loss_rate\x18\x05 \x01(\x01R\x0f\x66rame_loss_rate\x12\x38\n\x17imprecise_fixation_rate\x18\x06 \x01(\x01R\x17imprecise_fixation_rate\x12U\n\x10hit_rate_by_type\x18\x07 \x03(\x0b\x32).triald.v1.SimSettings.HitRateByTypeEntryR\x10hit_rate_by_type\x1a\x34\n\x12HitRateByTypeEntry\x12\x0b\n\x03key\x18\x01 \x01(\t\x12\r\n\x05value\x18\x02 \x01(\x01:\x02\x38\x01\"\x1d\n\x0bStepRequest\x12\x0e\n\x06trials\x18\x01 \x01(\x05\"\x8c\x01\n\nStepResult\x12\x0e\n\x06trials\x18\x01 \x01(\x05\x12\x0f\n\x07stopped\x18\x02 \x01(\x08\x12%\n\x0bstop_reason\x18\x03 \x01(\tH\x00R\x0bstop_reason\x88\x01\x01\x12&\n\x05state\x18\x04 \x01(\x0b\x32\x17.triald.v1.SessionStateB\x0e\n\x0c_stop_reason\"<\n\x07\x46reeRun\x12\x0f\n\x07running\x18\x01 \x01(\x08\x12 \n\x0binterval_ms\x18\x02 \x01(\x05R\x0binterval_ms\"B\n\rFreeRunStatus\x12\x0f\n\x07running\x18\x01 \x01(\x08\x12 \n\x0binterval_ms\x18\x02 \x01(\x05R\x0binterval_msb\x06proto3')

_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, globals())
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'triald.v1.debug_pb2', globals())
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  _SIMSETTINGS_HITRATEBYTYPEENTRY._options = None
  _SIMSETTINGS_HITRATEBYTYPEENTRY._serialized_options = b'8\001'
  _SIMSETTINGS._serialized_start=62
  _SIMSETTINGS._serialized_end=460
  _SIMSETTINGS_HITRATEBYTYPEENTRY._serialized_start=408
  _SIMSETTINGS_HITRATEBYTYPEENTRY._serialized_end=460
  _STEPREQUEST._serialized_start=462
  _STEPREQUEST._serialized_end=491
  _STEPRESULT._serialized_start=494
  _STEPRESULT._serialized_end=634
  _FREERUN._serialized_start=636
  _FREERUN._serialized_end=696
  _FREERUNSTATUS._serialized_start=698
  _FREERUNSTATUS._serialized_end=764
# @@protoc_insertion_point(module_scope)
