# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
import warnings

from triald._proto.triald.v1 import common_pb2 as triald_dot_v1_dot_common__pb2
from triald._proto.triald.v1 import config_pb2 as triald_dot_v1_dot_config__pb2
from triald._proto.triald.v1 import debug_pb2 as triald_dot_v1_dot_debug__pb2
from triald._proto.triald.v1 import policy_pb2 as triald_dot_v1_dot_policy__pb2
from triald._proto.triald.v1 import service_pb2 as triald_dot_v1_dot_service__pb2
from triald._proto.triald.v1 import session_pb2 as triald_dot_v1_dot_session__pb2
from triald._proto.triald.v1 import sets_pb2 as triald_dot_v1_dot_sets__pb2
from triald._proto.triald.v1 import trial_pb2 as triald_dot_v1_dot_trial__pb2

GRPC_GENERATED_VERSION = '1.84.0'
GRPC_VERSION = grpc.__version__
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower
    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    raise RuntimeError(
        f'The grpc package installed is at version {GRPC_VERSION},'
        + ' but the generated code in triald/v1/service_pb2_grpc.py depends on'
        + f' grpcio>={GRPC_GENERATED_VERSION}.'
        + f' Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}'
        + f' or downgrade your generated code using grpcio-tools<={GRPC_VERSION}.'
    )


class StateStub:
    """What is happening, and who is watching.
    """

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.ReadState = channel.unary_unary(
                '/triald.v1.State/ReadState',
                request_serializer=triald_dot_v1_dot_service__pb2.ReadStateRequest.SerializeToString,
                response_deserializer=triald_dot_v1_dot_session__pb2.SessionState.FromString,
                _registered_method=True)
        self.WatchState = channel.unary_stream(
                '/triald.v1.State/WatchState',
                request_serializer=triald_dot_v1_dot_service__pb2.WatchStateRequest.SerializeToString,
                response_deserializer=triald_dot_v1_dot_session__pb2.StreamFrame.FromString,
                _registered_method=True)


class StateServicer:
    """What is happening, and who is watching.
    """

    def ReadState(self, request, context):
        """Everything true right now, in one answer.
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def WatchState(self, request, context):
        """The same thing, pushed.

        Frames are coalesced under load — `sequence` skips, and that is not loss:
        each frame is a whole state, so the newest one is always the truth. A
        client that missed three frames has missed nothing it could have used.
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_StateServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'ReadState': grpc.unary_unary_rpc_method_handler(
                    servicer.ReadState,
                    request_deserializer=triald_dot_v1_dot_service__pb2.ReadStateRequest.FromString,
                    response_serializer=triald_dot_v1_dot_session__pb2.SessionState.SerializeToString,
            ),
            'WatchState': grpc.unary_stream_rpc_method_handler(
                    servicer.WatchState,
                    request_deserializer=triald_dot_v1_dot_service__pb2.WatchStateRequest.FromString,
                    response_serializer=triald_dot_v1_dot_session__pb2.StreamFrame.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'triald.v1.State', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('triald.v1.State', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class State:
    """What is happening, and who is watching.
    """

    @staticmethod
    def ReadState(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/triald.v1.State/ReadState',
            triald_dot_v1_dot_service__pb2.ReadStateRequest.SerializeToString,
            triald_dot_v1_dot_session__pb2.SessionState.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def WatchState(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_stream(
            request,
            target,
            '/triald.v1.State/WatchState',
            triald_dot_v1_dot_service__pb2.WatchStateRequest.SerializeToString,
            triald_dot_v1_dot_session__pb2.StreamFrame.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)


class SessionStub:
    """Starting and stopping, and what gets written to disk.

    **Arming and recording are two switches, deliberately.** A session can run
    without recording — that is what a warm-up is — and recording can be paused
    mid-session without losing where the round had got to.
    """

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.Arm = channel.unary_unary(
                '/triald.v1.Session/Arm',
                request_serializer=triald_dot_v1_dot_service__pb2.ArmRequest.SerializeToString,
                response_deserializer=triald_dot_v1_dot_session__pb2.SessionState.FromString,
                _registered_method=True)
        self.Stop = channel.unary_unary(
                '/triald.v1.Session/Stop',
                request_serializer=triald_dot_v1_dot_service__pb2.StopRequest.SerializeToString,
                response_deserializer=triald_dot_v1_dot_session__pb2.SessionState.FromString,
                _registered_method=True)
        self.StartRecording = channel.unary_unary(
                '/triald.v1.Session/StartRecording',
                request_serializer=triald_dot_v1_dot_service__pb2.StartRecordingRequest.SerializeToString,
                response_deserializer=triald_dot_v1_dot_session__pb2.SessionState.FromString,
                _registered_method=True)
        self.PauseRecording = channel.unary_unary(
                '/triald.v1.Session/PauseRecording',
                request_serializer=triald_dot_v1_dot_service__pb2.PauseRecordingRequest.SerializeToString,
                response_deserializer=triald_dot_v1_dot_session__pb2.SessionState.FromString,
                _registered_method=True)
        self.ResumeRecording = channel.unary_unary(
                '/triald.v1.Session/ResumeRecording',
                request_serializer=triald_dot_v1_dot_service__pb2.ResumeRecordingRequest.SerializeToString,
                response_deserializer=triald_dot_v1_dot_session__pb2.SessionState.FromString,
                _registered_method=True)
        self.StopRecording = channel.unary_unary(
                '/triald.v1.Session/StopRecording',
                request_serializer=triald_dot_v1_dot_service__pb2.StopRecordingRequest.SerializeToString,
                response_deserializer=triald_dot_v1_dot_session__pb2.SessionState.FromString,
                _registered_method=True)


class SessionServicer:
    """Starting and stopping, and what gets written to disk.

    **Arming and recording are two switches, deliberately.** A session can run
    without recording — that is what a warm-up is — and recording can be paused
    mid-session without losing where the round had got to.
    """

    def Arm(self, request, context):
        """Build a session from the config and the active set, and refuse if the
        switch rules reachable from that set do not hang together.
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def Stop(self, request, context):
        """End the session. The reason is recorded and shown.
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def StartRecording(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def PauseRecording(self, request, context):
        """Stop writing, keeping the session. A trial already in flight finishes
        recording: `recording` is latched on the trial at selection.
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def ResumeRecording(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def StopRecording(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_SessionServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'Arm': grpc.unary_unary_rpc_method_handler(
                    servicer.Arm,
                    request_deserializer=triald_dot_v1_dot_service__pb2.ArmRequest.FromString,
                    response_serializer=triald_dot_v1_dot_session__pb2.SessionState.SerializeToString,
            ),
            'Stop': grpc.unary_unary_rpc_method_handler(
                    servicer.Stop,
                    request_deserializer=triald_dot_v1_dot_service__pb2.StopRequest.FromString,
                    response_serializer=triald_dot_v1_dot_session__pb2.SessionState.SerializeToString,
            ),
            'StartRecording': grpc.unary_unary_rpc_method_handler(
                    servicer.StartRecording,
                    request_deserializer=triald_dot_v1_dot_service__pb2.StartRecordingRequest.FromString,
                    response_serializer=triald_dot_v1_dot_session__pb2.SessionState.SerializeToString,
            ),
            'PauseRecording': grpc.unary_unary_rpc_method_handler(
                    servicer.PauseRecording,
                    request_deserializer=triald_dot_v1_dot_service__pb2.PauseRecordingRequest.FromString,
                    response_serializer=triald_dot_v1_dot_session__pb2.SessionState.SerializeToString,
            ),
            'ResumeRecording': grpc.unary_unary_rpc_method_handler(
                    servicer.ResumeRecording,
                    request_deserializer=triald_dot_v1_dot_service__pb2.ResumeRecordingRequest.FromString,
                    response_serializer=triald_dot_v1_dot_session__pb2.SessionState.SerializeToString,
            ),
            'StopRecording': grpc.unary_unary_rpc_method_handler(
                    servicer.StopRecording,
                    request_deserializer=triald_dot_v1_dot_service__pb2.StopRecordingRequest.FromString,
                    response_serializer=triald_dot_v1_dot_session__pb2.SessionState.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'triald.v1.Session', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('triald.v1.Session', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class Session:
    """Starting and stopping, and what gets written to disk.

    **Arming and recording are two switches, deliberately.** A session can run
    without recording — that is what a warm-up is — and recording can be paused
    mid-session without losing where the round had got to.
    """

    @staticmethod
    def Arm(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/triald.v1.Session/Arm',
            triald_dot_v1_dot_service__pb2.ArmRequest.SerializeToString,
            triald_dot_v1_dot_session__pb2.SessionState.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def Stop(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/triald.v1.Session/Stop',
            triald_dot_v1_dot_service__pb2.StopRequest.SerializeToString,
            triald_dot_v1_dot_session__pb2.SessionState.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def StartRecording(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/triald.v1.Session/StartRecording',
            triald_dot_v1_dot_service__pb2.StartRecordingRequest.SerializeToString,
            triald_dot_v1_dot_session__pb2.SessionState.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def PauseRecording(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/triald.v1.Session/PauseRecording',
            triald_dot_v1_dot_service__pb2.PauseRecordingRequest.SerializeToString,
            triald_dot_v1_dot_session__pb2.SessionState.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def ResumeRecording(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/triald.v1.Session/ResumeRecording',
            triald_dot_v1_dot_service__pb2.ResumeRecordingRequest.SerializeToString,
            triald_dot_v1_dot_session__pb2.SessionState.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def StopRecording(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/triald.v1.Session/StopRecording',
            triald_dot_v1_dot_service__pb2.StopRecordingRequest.SerializeToString,
            triald_dot_v1_dot_session__pb2.SessionState.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)


class TrialStub:
    """One trial, from selection to outcome.

    **This is the loop.** Whatever runs a trial asks for the next one, runs it,
    and reports what happened; this daemon decides and records. It commands its
    participants and subscribes to what they publish, and they command nobody —
    `contracts/INTERACTIONS.md` §2.
    """

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.Next = channel.unary_unary(
                '/triald.v1.Trial/Next',
                request_serializer=triald_dot_v1_dot_service__pb2.NextTrialRequest.SerializeToString,
                response_deserializer=triald_dot_v1_dot_trial__pb2.TrialSpec.FromString,
                _registered_method=True)
        self.ReportOutcome = channel.unary_unary(
                '/triald.v1.Trial/ReportOutcome',
                request_serializer=triald_dot_v1_dot_trial__pb2.OutcomeReport.SerializeToString,
                response_deserializer=triald_dot_v1_dot_trial__pb2.TrialRecord.FromString,
                _registered_method=True)
        self.Cancel = channel.unary_unary(
                '/triald.v1.Trial/Cancel',
                request_serializer=triald_dot_v1_dot_trial__pb2.CancelTrial.SerializeToString,
                response_deserializer=triald_dot_v1_dot_trial__pb2.TrialRecord.FromString,
                _registered_method=True)


class TrialServicer:
    """One trial, from selection to outcome.

    **This is the loop.** Whatever runs a trial asks for the next one, runs it,
    and reports what happened; this daemon decides and records. It commands its
    participants and subscribes to what they publish, and they command nobody —
    `contracts/INTERACTIONS.md` §2.
    """

    def Next(self, request, context):
        """Select the next trial and publish it. The selection is latched: asking
        twice without reporting an outcome is an error, not a redraw.
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def ReportOutcome(self, request, context):
        """Report how a trial ended, and get back the record it became.

        Refuses `failed_precondition` when `trial_id` is not the trial in flight:
        a report that arrived late or twice must never be attributed to the trial
        after the one it belongs to. That refusal carries `error: "trial_mismatch"`
        — its own kind, because it is the one a *correct* caller can hit, and the
        answer is to drop the report rather than retry it.

        The record says whether the trial was *accepted*, which is not the same as
        counted, and names which check refused it.
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def Cancel(self, request, context):
        """Abandon the trial in flight. It is recorded as `CANCELLED` rather than
        discarded: a trial that happened to an animal happened.
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_TrialServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'Next': grpc.unary_unary_rpc_method_handler(
                    servicer.Next,
                    request_deserializer=triald_dot_v1_dot_service__pb2.NextTrialRequest.FromString,
                    response_serializer=triald_dot_v1_dot_trial__pb2.TrialSpec.SerializeToString,
            ),
            'ReportOutcome': grpc.unary_unary_rpc_method_handler(
                    servicer.ReportOutcome,
                    request_deserializer=triald_dot_v1_dot_trial__pb2.OutcomeReport.FromString,
                    response_serializer=triald_dot_v1_dot_trial__pb2.TrialRecord.SerializeToString,
            ),
            'Cancel': grpc.unary_unary_rpc_method_handler(
                    servicer.Cancel,
                    request_deserializer=triald_dot_v1_dot_trial__pb2.CancelTrial.FromString,
                    response_serializer=triald_dot_v1_dot_trial__pb2.TrialRecord.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'triald.v1.Trial', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('triald.v1.Trial', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class Trial:
    """One trial, from selection to outcome.

    **This is the loop.** Whatever runs a trial asks for the next one, runs it,
    and reports what happened; this daemon decides and records. It commands its
    participants and subscribes to what they publish, and they command nobody —
    `contracts/INTERACTIONS.md` §2.
    """

    @staticmethod
    def Next(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/triald.v1.Trial/Next',
            triald_dot_v1_dot_service__pb2.NextTrialRequest.SerializeToString,
            triald_dot_v1_dot_trial__pb2.TrialSpec.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def ReportOutcome(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/triald.v1.Trial/ReportOutcome',
            triald_dot_v1_dot_trial__pb2.OutcomeReport.SerializeToString,
            triald_dot_v1_dot_trial__pb2.TrialRecord.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def Cancel(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/triald.v1.Trial/Cancel',
            triald_dot_v1_dot_trial__pb2.CancelTrial.SerializeToString,
            triald_dot_v1_dot_trial__pb2.TrialRecord.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)


class SetStoreStub:
    """The trial types, in named sets.
    """

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.ReadSets = channel.unary_unary(
                '/triald.v1.SetStore/ReadSets',
                request_serializer=triald_dot_v1_dot_service__pb2.ReadSetsRequest.SerializeToString,
                response_deserializer=triald_dot_v1_dot_sets__pb2.Sets.FromString,
                _registered_method=True)
        self.WriteSet = channel.unary_unary(
                '/triald.v1.SetStore/WriteSet',
                request_serializer=triald_dot_v1_dot_sets__pb2.WriteSetRequest.SerializeToString,
                response_deserializer=triald_dot_v1_dot_sets__pb2.Sets.FromString,
                _registered_method=True)
        self.DeleteSet = channel.unary_unary(
                '/triald.v1.SetStore/DeleteSet',
                request_serializer=triald_dot_v1_dot_sets__pb2.SetName.SerializeToString,
                response_deserializer=triald_dot_v1_dot_sets__pb2.Sets.FromString,
                _registered_method=True)
        self.LoadSet = channel.unary_unary(
                '/triald.v1.SetStore/LoadSet',
                request_serializer=triald_dot_v1_dot_sets__pb2.SetName.SerializeToString,
                response_deserializer=triald_dot_v1_dot_session__pb2.SessionState.FromString,
                _registered_method=True)


class SetStoreServicer:
    """The trial types, in named sets.
    """

    def ReadSets(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def WriteSet(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def DeleteSet(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def LoadSet(self, request, context):
        """Make a set active. Refused while a session is armed: the bag was built
        from the set that was active when it was.
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_SetStoreServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'ReadSets': grpc.unary_unary_rpc_method_handler(
                    servicer.ReadSets,
                    request_deserializer=triald_dot_v1_dot_service__pb2.ReadSetsRequest.FromString,
                    response_serializer=triald_dot_v1_dot_sets__pb2.Sets.SerializeToString,
            ),
            'WriteSet': grpc.unary_unary_rpc_method_handler(
                    servicer.WriteSet,
                    request_deserializer=triald_dot_v1_dot_sets__pb2.WriteSetRequest.FromString,
                    response_serializer=triald_dot_v1_dot_sets__pb2.Sets.SerializeToString,
            ),
            'DeleteSet': grpc.unary_unary_rpc_method_handler(
                    servicer.DeleteSet,
                    request_deserializer=triald_dot_v1_dot_sets__pb2.SetName.FromString,
                    response_serializer=triald_dot_v1_dot_sets__pb2.Sets.SerializeToString,
            ),
            'LoadSet': grpc.unary_unary_rpc_method_handler(
                    servicer.LoadSet,
                    request_deserializer=triald_dot_v1_dot_sets__pb2.SetName.FromString,
                    response_serializer=triald_dot_v1_dot_session__pb2.SessionState.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'triald.v1.SetStore', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('triald.v1.SetStore', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class SetStore:
    """The trial types, in named sets.
    """

    @staticmethod
    def ReadSets(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/triald.v1.SetStore/ReadSets',
            triald_dot_v1_dot_service__pb2.ReadSetsRequest.SerializeToString,
            triald_dot_v1_dot_sets__pb2.Sets.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def WriteSet(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/triald.v1.SetStore/WriteSet',
            triald_dot_v1_dot_sets__pb2.WriteSetRequest.SerializeToString,
            triald_dot_v1_dot_sets__pb2.Sets.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def DeleteSet(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/triald.v1.SetStore/DeleteSet',
            triald_dot_v1_dot_sets__pb2.SetName.SerializeToString,
            triald_dot_v1_dot_sets__pb2.Sets.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def LoadSet(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/triald.v1.SetStore/LoadSet',
            triald_dot_v1_dot_sets__pb2.SetName.SerializeToString,
            triald_dot_v1_dot_session__pb2.SessionState.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)


class ConfigStub:
    """The session's declarative settings.
    """

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.ReadConfig = channel.unary_unary(
                '/triald.v1.Config/ReadConfig',
                request_serializer=triald_dot_v1_dot_service__pb2.ReadConfigRequest.SerializeToString,
                response_deserializer=triald_dot_v1_dot_config__pb2.SessionConfig.FromString,
                _registered_method=True)
        self.PatchConfig = channel.unary_unary(
                '/triald.v1.Config/PatchConfig',
                request_serializer=triald_dot_v1_dot_config__pb2.ConfigPatch.SerializeToString,
                response_deserializer=triald_dot_v1_dot_config__pb2.ConfigUpdateResult.FromString,
                _registered_method=True)
        self.ResetRounds = channel.unary_unary(
                '/triald.v1.Config/ResetRounds',
                request_serializer=triald_dot_v1_dot_service__pb2.ResetRoundsRequest.SerializeToString,
                response_deserializer=triald_dot_v1_dot_session__pb2.SessionState.FromString,
                _registered_method=True)
        self.ResetCounters = channel.unary_unary(
                '/triald.v1.Config/ResetCounters',
                request_serializer=triald_dot_v1_dot_service__pb2.ResetCountersRequest.SerializeToString,
                response_deserializer=triald_dot_v1_dot_session__pb2.SessionState.FromString,
                _registered_method=True)


class ConfigServicer:
    """The session's declarative settings.
    """

    def ReadConfig(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def PatchConfig(self, request, context):
        """Change some of it. What may change while a session runs is the daemon's
        decision, and the answer says what actually changed and whether the round
        restarted because the bag had to be rebuilt.
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def ResetRounds(self, request, context):
        """Start the round count again without touching the counters.
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def ResetCounters(self, request, context):
        """Zero the tallies without touching the round.
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_ConfigServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'ReadConfig': grpc.unary_unary_rpc_method_handler(
                    servicer.ReadConfig,
                    request_deserializer=triald_dot_v1_dot_service__pb2.ReadConfigRequest.FromString,
                    response_serializer=triald_dot_v1_dot_config__pb2.SessionConfig.SerializeToString,
            ),
            'PatchConfig': grpc.unary_unary_rpc_method_handler(
                    servicer.PatchConfig,
                    request_deserializer=triald_dot_v1_dot_config__pb2.ConfigPatch.FromString,
                    response_serializer=triald_dot_v1_dot_config__pb2.ConfigUpdateResult.SerializeToString,
            ),
            'ResetRounds': grpc.unary_unary_rpc_method_handler(
                    servicer.ResetRounds,
                    request_deserializer=triald_dot_v1_dot_service__pb2.ResetRoundsRequest.FromString,
                    response_serializer=triald_dot_v1_dot_session__pb2.SessionState.SerializeToString,
            ),
            'ResetCounters': grpc.unary_unary_rpc_method_handler(
                    servicer.ResetCounters,
                    request_deserializer=triald_dot_v1_dot_service__pb2.ResetCountersRequest.FromString,
                    response_serializer=triald_dot_v1_dot_session__pb2.SessionState.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'triald.v1.Config', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('triald.v1.Config', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class Config:
    """The session's declarative settings.
    """

    @staticmethod
    def ReadConfig(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/triald.v1.Config/ReadConfig',
            triald_dot_v1_dot_service__pb2.ReadConfigRequest.SerializeToString,
            triald_dot_v1_dot_config__pb2.SessionConfig.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def PatchConfig(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/triald.v1.Config/PatchConfig',
            triald_dot_v1_dot_config__pb2.ConfigPatch.SerializeToString,
            triald_dot_v1_dot_config__pb2.ConfigUpdateResult.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def ResetRounds(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/triald.v1.Config/ResetRounds',
            triald_dot_v1_dot_service__pb2.ResetRoundsRequest.SerializeToString,
            triald_dot_v1_dot_session__pb2.SessionState.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def ResetCounters(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/triald.v1.Config/ResetCounters',
            triald_dot_v1_dot_service__pb2.ResetCountersRequest.SerializeToString,
            triald_dot_v1_dot_session__pb2.SessionState.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)


class PolicyStub:
    """The Python that decides what happens next, when the declarative settings are
    not enough.
    """

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.ReadPolicy = channel.unary_unary(
                '/triald.v1.Policy/ReadPolicy',
                request_serializer=triald_dot_v1_dot_service__pb2.ReadPolicyRequest.SerializeToString,
                response_deserializer=triald_dot_v1_dot_policy__pb2.PolicyInfo.FromString,
                _registered_method=True)
        self.CheckPolicy = channel.unary_unary(
                '/triald.v1.Policy/CheckPolicy',
                request_serializer=triald_dot_v1_dot_policy__pb2.PolicySource.SerializeToString,
                response_deserializer=triald_dot_v1_dot_policy__pb2.PolicyCheckResult.FromString,
                _registered_method=True)
        self.LoadPolicy = channel.unary_unary(
                '/triald.v1.Policy/LoadPolicy',
                request_serializer=triald_dot_v1_dot_policy__pb2.PolicySource.SerializeToString,
                response_deserializer=triald_dot_v1_dot_policy__pb2.PolicyInfo.FromString,
                _registered_method=True)
        self.ClearPolicy = channel.unary_unary(
                '/triald.v1.Policy/ClearPolicy',
                request_serializer=triald_dot_v1_dot_service__pb2.ClearPolicyRequest.SerializeToString,
                response_deserializer=triald_dot_v1_dot_policy__pb2.PolicyInfo.FromString,
                _registered_method=True)


class PolicyServicer:
    """The Python that decides what happens next, when the declarative settings are
    not enough.
    """

    def ReadPolicy(self, request, context):
        """`source` asks for the policy's text, which is large and usually not wanted.
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def CheckPolicy(self, request, context):
        """Compile it, import it, and run it over a short simulated session — without
        loading it. A policy that raises on trial 200 is worth finding out about
        before there is an animal in the rig.
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def LoadPolicy(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def ClearPolicy(self, request, context):
        """Go back to the declarative ordering.
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_PolicyServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'ReadPolicy': grpc.unary_unary_rpc_method_handler(
                    servicer.ReadPolicy,
                    request_deserializer=triald_dot_v1_dot_service__pb2.ReadPolicyRequest.FromString,
                    response_serializer=triald_dot_v1_dot_policy__pb2.PolicyInfo.SerializeToString,
            ),
            'CheckPolicy': grpc.unary_unary_rpc_method_handler(
                    servicer.CheckPolicy,
                    request_deserializer=triald_dot_v1_dot_policy__pb2.PolicySource.FromString,
                    response_serializer=triald_dot_v1_dot_policy__pb2.PolicyCheckResult.SerializeToString,
            ),
            'LoadPolicy': grpc.unary_unary_rpc_method_handler(
                    servicer.LoadPolicy,
                    request_deserializer=triald_dot_v1_dot_policy__pb2.PolicySource.FromString,
                    response_serializer=triald_dot_v1_dot_policy__pb2.PolicyInfo.SerializeToString,
            ),
            'ClearPolicy': grpc.unary_unary_rpc_method_handler(
                    servicer.ClearPolicy,
                    request_deserializer=triald_dot_v1_dot_service__pb2.ClearPolicyRequest.FromString,
                    response_serializer=triald_dot_v1_dot_policy__pb2.PolicyInfo.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'triald.v1.Policy', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('triald.v1.Policy', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class Policy:
    """The Python that decides what happens next, when the declarative settings are
    not enough.
    """

    @staticmethod
    def ReadPolicy(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/triald.v1.Policy/ReadPolicy',
            triald_dot_v1_dot_service__pb2.ReadPolicyRequest.SerializeToString,
            triald_dot_v1_dot_policy__pb2.PolicyInfo.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def CheckPolicy(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/triald.v1.Policy/CheckPolicy',
            triald_dot_v1_dot_policy__pb2.PolicySource.SerializeToString,
            triald_dot_v1_dot_policy__pb2.PolicyCheckResult.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def LoadPolicy(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/triald.v1.Policy/LoadPolicy',
            triald_dot_v1_dot_policy__pb2.PolicySource.SerializeToString,
            triald_dot_v1_dot_policy__pb2.PolicyInfo.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def ClearPolicy(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/triald.v1.Policy/ClearPolicy',
            triald_dot_v1_dot_service__pb2.ClearPolicyRequest.SerializeToString,
            triald_dot_v1_dot_policy__pb2.PolicyInfo.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)


class EventsStub:
    """Things that happened that nothing else records.
    """

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.Note = channel.unary_unary(
                '/triald.v1.Events/Note',
                request_serializer=triald_dot_v1_dot_session__pb2.NoteRequest.SerializeToString,
                response_deserializer=triald_dot_v1_dot_common__pb2.Ok.FromString,
                _registered_method=True)


class EventsServicer:
    """Things that happened that nothing else records.
    """

    def Note(self, request, context):
        """Append an experimenter's note to the session's event stream.
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_EventsServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'Note': grpc.unary_unary_rpc_method_handler(
                    servicer.Note,
                    request_deserializer=triald_dot_v1_dot_session__pb2.NoteRequest.FromString,
                    response_serializer=triald_dot_v1_dot_common__pb2.Ok.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'triald.v1.Events', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('triald.v1.Events', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class Events:
    """Things that happened that nothing else records.
    """

    @staticmethod
    def Note(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/triald.v1.Events/Note',
            triald_dot_v1_dot_session__pb2.NoteRequest.SerializeToString,
            triald_dot_v1_dot_common__pb2.Ok.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)


class DebugStub:
    """A synthetic subject, so a policy can be run over 500 trials in a second.

    **Not a model of behaviour and not meant to be.** It exists so that logic can
    be checked before anything is connected to a rig, and so this UI can be
    driven with no hardware at all.
    """

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.ReadSim = channel.unary_unary(
                '/triald.v1.Debug/ReadSim',
                request_serializer=triald_dot_v1_dot_service__pb2.ReadSimRequest.SerializeToString,
                response_deserializer=triald_dot_v1_dot_debug__pb2.SimSettings.FromString,
                _registered_method=True)
        self.WriteSim = channel.unary_unary(
                '/triald.v1.Debug/WriteSim',
                request_serializer=triald_dot_v1_dot_debug__pb2.SimSettings.SerializeToString,
                response_deserializer=triald_dot_v1_dot_debug__pb2.SimSettings.FromString,
                _registered_method=True)
        self.Step = channel.unary_unary(
                '/triald.v1.Debug/Step',
                request_serializer=triald_dot_v1_dot_debug__pb2.StepRequest.SerializeToString,
                response_deserializer=triald_dot_v1_dot_debug__pb2.StepResult.FromString,
                _registered_method=True)
        self.ReadFreeRun = channel.unary_unary(
                '/triald.v1.Debug/ReadFreeRun',
                request_serializer=triald_dot_v1_dot_service__pb2.ReadFreeRunRequest.SerializeToString,
                response_deserializer=triald_dot_v1_dot_debug__pb2.FreeRunStatus.FromString,
                _registered_method=True)
        self.WriteFreeRun = channel.unary_unary(
                '/triald.v1.Debug/WriteFreeRun',
                request_serializer=triald_dot_v1_dot_debug__pb2.FreeRun.SerializeToString,
                response_deserializer=triald_dot_v1_dot_debug__pb2.FreeRunStatus.FromString,
                _registered_method=True)


class DebugServicer:
    """A synthetic subject, so a policy can be run over 500 trials in a second.

    **Not a model of behaviour and not meant to be.** It exists so that logic can
    be checked before anything is connected to a rig, and so this UI can be
    driven with no hardware at all.
    """

    def ReadSim(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def WriteSim(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def Step(self, request, context):
        """Run whole simulated trials, now.
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def ReadFreeRun(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def WriteFreeRun(self, request, context):
        """Step the simulator on a timer until it is stopped or the session ends.
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_DebugServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'ReadSim': grpc.unary_unary_rpc_method_handler(
                    servicer.ReadSim,
                    request_deserializer=triald_dot_v1_dot_service__pb2.ReadSimRequest.FromString,
                    response_serializer=triald_dot_v1_dot_debug__pb2.SimSettings.SerializeToString,
            ),
            'WriteSim': grpc.unary_unary_rpc_method_handler(
                    servicer.WriteSim,
                    request_deserializer=triald_dot_v1_dot_debug__pb2.SimSettings.FromString,
                    response_serializer=triald_dot_v1_dot_debug__pb2.SimSettings.SerializeToString,
            ),
            'Step': grpc.unary_unary_rpc_method_handler(
                    servicer.Step,
                    request_deserializer=triald_dot_v1_dot_debug__pb2.StepRequest.FromString,
                    response_serializer=triald_dot_v1_dot_debug__pb2.StepResult.SerializeToString,
            ),
            'ReadFreeRun': grpc.unary_unary_rpc_method_handler(
                    servicer.ReadFreeRun,
                    request_deserializer=triald_dot_v1_dot_service__pb2.ReadFreeRunRequest.FromString,
                    response_serializer=triald_dot_v1_dot_debug__pb2.FreeRunStatus.SerializeToString,
            ),
            'WriteFreeRun': grpc.unary_unary_rpc_method_handler(
                    servicer.WriteFreeRun,
                    request_deserializer=triald_dot_v1_dot_debug__pb2.FreeRun.FromString,
                    response_serializer=triald_dot_v1_dot_debug__pb2.FreeRunStatus.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'triald.v1.Debug', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('triald.v1.Debug', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class Debug:
    """A synthetic subject, so a policy can be run over 500 trials in a second.

    **Not a model of behaviour and not meant to be.** It exists so that logic can
    be checked before anything is connected to a rig, and so this UI can be
    driven with no hardware at all.
    """

    @staticmethod
    def ReadSim(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/triald.v1.Debug/ReadSim',
            triald_dot_v1_dot_service__pb2.ReadSimRequest.SerializeToString,
            triald_dot_v1_dot_debug__pb2.SimSettings.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def WriteSim(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/triald.v1.Debug/WriteSim',
            triald_dot_v1_dot_debug__pb2.SimSettings.SerializeToString,
            triald_dot_v1_dot_debug__pb2.SimSettings.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def Step(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/triald.v1.Debug/Step',
            triald_dot_v1_dot_debug__pb2.StepRequest.SerializeToString,
            triald_dot_v1_dot_debug__pb2.StepResult.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def ReadFreeRun(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/triald.v1.Debug/ReadFreeRun',
            triald_dot_v1_dot_service__pb2.ReadFreeRunRequest.SerializeToString,
            triald_dot_v1_dot_debug__pb2.FreeRunStatus.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def WriteFreeRun(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/triald.v1.Debug/WriteFreeRun',
            triald_dot_v1_dot_debug__pb2.FreeRun.SerializeToString,
            triald_dot_v1_dot_debug__pb2.FreeRunStatus.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
