# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: triald/v1/outcomes.proto
# Protobuf Python Version: 7.35.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    7,
    35,
    1,
    '',
    'triald/v1/outcomes.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x18triald/v1/outcomes.proto\x12\ttriald.v1*\xfc\x01\n\x0cTrialOutcome\x12\x0f\n\x0bNOT_STARTED\x10\x00\x12\x19\n\x0cUNDETERMINED\x10\xff\xff\xff\xff\xff\xff\xff\xff\xff\x01\x12\x07\n\x03HIT\x10\x01\x12\x12\n\x0eWRONG_RESPONSE\x10\x02\x12\r\n\tEARLY_HIT\x10\x03\x12\x18\n\x14\x45\x41RLY_WRONG_RESPONSE\x10\x04\x12\t\n\x05\x45\x41RLY\x10\x05\x12\x08\n\x04LATE\x10\x06\x12\r\n\tEYE_ERROR\x10\x07\x12\x1b\n\x17UNEXPECTED_START_SIGNAL\x10\x08\x12\x16\n\x12WRONG_START_SIGNAL\x10\t\x12\r\n\tCANCELLED\x10\n\x12\x12\n\x0eNEVER_FINISHED\x10\x0b\x62\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'triald.v1.outcomes_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_TRIALOUTCOME']._serialized_start=40
  _globals['_TRIALOUTCOME']._serialized_end=292
# @@protoc_insertion_point(module_scope)
