# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: triald/v1/sets.proto
# Protobuf Python Version: 7.35.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    7,
    35,
    1,
    '',
    'triald/v1/sets.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from google.protobuf import struct_pb2 as google_dot_protobuf_dot_struct__pb2
from triald_client._proto.triald.v1 import common_pb2 as triald_dot_v1_dot_common__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x14triald/v1/sets.proto\x12\ttriald.v1\x1a\x1cgoogle/protobuf/struct.proto\x1a\x16triald/v1/common.proto\"\x7f\n\nSwitchRule\x12\x0f\n\x07\x65nabled\x18\x01 \x01(\x08\x12\x31\n\tcriterion\x18\x02 \x01(\x0e\x32\x1e.triald.v1.TrialCountCriterion\x12\r\n\x05\x63ount\x18\x03 \x01(\x05\x12\x13\n\x06target\x18\x04 \x01(\tH\x00\x88\x01\x01\x42\t\n\x07_target\"\xbc\x01\n\tTrialType\x12\x0c\n\x04name\x18\x01 \x01(\t\x12*\n\x10trials_per_round\x18\x02 \x01(\x05R\x10trials_per_round\x12.\n\x12statemachine_graph\x18\x03 \x01(\tR\x12statemachine_graph\x12\x1c\n\treward_ms\x18\x04 \x01(\x05R\treward_ms\x12\'\n\x06params\x18\x05 \x01(\x0b\x32\x17.google.protobuf.Struct\"\xfb\x01\n\x0cTrialTypeSet\x12\x0c\n\x04name\x18\x01 \x01(\t\x12\x36\n\x0btrial_types\x18\x02 \x03(\x0b\x32\x14.triald.v1.TrialTypeR\x0btrial_types\x12\x37\n\x0bswitch_rule\x18\x03 \x01(\x0b\x32\x15.triald.v1.SwitchRuleR\x0bswitch_rule\x12*\n\x10trials_per_round\x18\x04 \x01(\x05R\x10trials_per_round\x12\x10\n\x08runnable\x18\x05 \x01(\x08\x12\x1e\n\nset_number\x18\x06 \x01(\x05R\nset_number\x12\x0e\n\x06\x61\x63tive\x18\x07 \x01(\x08\"\x8a\x01\n\x04Sets\x12%\n\x04sets\x18\x01 \x03(\x0b\x32\x17.triald.v1.TrialTypeSet\x12\x13\n\x06\x61\x63tive\x18\x02 \x01(\tH\x00\x88\x01\x01\x12)\n\rchain_problem\x18\x03 \x01(\tH\x01R\rchain_problem\x88\x01\x01\x42\t\n\x07_activeB\x10\n\x0e_chain_problem\"\x17\n\x07SetName\x12\x0c\n\x04name\x18\x01 \x01(\t\"E\n\x0fWriteSetRequest\x12\x0c\n\x04name\x18\x01 \x01(\t\x12$\n\x03set\x18\x02 \x01(\x0b\x32\x17.triald.v1.TrialTypeSetb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'triald.v1.sets_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_SWITCHRULE']._serialized_start=89
  _globals['_SWITCHRULE']._serialized_end=216
  _globals['_TRIALTYPE']._serialized_start=219
  _globals['_TRIALTYPE']._serialized_end=407
  _globals['_TRIALTYPESET']._serialized_start=410
  _globals['_TRIALTYPESET']._serialized_end=661
  _globals['_SETS']._serialized_start=664
  _globals['_SETS']._serialized_end=802
  _globals['_SETNAME']._serialized_start=804
  _globals['_SETNAME']._serialized_end=827
  _globals['_WRITESETREQUEST']._serialized_start=829
  _globals['_WRITESETREQUEST']._serialized_end=898
# @@protoc_insertion_point(module_scope)
