#!/usr/bin/env python3
# SPDX-License-Identifier: AGPL-3.0-or-later
"""Write `proto/triald/v1/outcomes.proto` from the vendored `outcomes.json`.

**The outcome taxonomy is data, not this daemon's interface.** It belongs to the
family — `contracts/INTERACTIONS.md` §6 — and is carried as a vendored copy in
five places precisely so that nothing has to depend on anything to read it. A
hand-written proto enum would be a sixth copy, with the same name drift the
checker exists to catch and none of its protection.

So this one is **generated and checked**, the way the schema of a zone set is in
mousewheeld: `make proto` writes it, `make check-proto` regenerates it and fails
on a difference, and the authored copy stays the JSON.

Two decisions worth knowing, both of them deliberate:

*   **The enum's value names are the taxonomy's names, with no prefix.** Proto
    style would spell them `TRIAL_OUTCOME_HIT`, and protobuf's JSON mapping puts
    the value name on the wire — so the prefix would mean a client sending
    `"TRIAL_OUTCOME_HIT"` where every other copy of this table, every `.tdr`
    file and every analysis script says `HIT`. §7 records that
    `schemas.py` exists so a scientist can send `"HIT"` rather than `1`; that
    commitment survives here, and buf's ENUM_VALUE_PREFIX rule is waived for
    this one file because of it.

*   **The numbers are the `.tdr` codes**, including `UNDETERMINED = -1`. Field
    numbers in a proto enum are already "never renumbered, a value once used is
    used for ever", which is exactly the rule the JSON file states in prose.
    proto3 needs a zero first, and `NOT_STARTED = 0` obliges.
"""

from __future__ import annotations

import argparse
import json
import sys
from pathlib import Path

HERE = Path(__file__).resolve().parent.parent
TAXONOMY = HERE / "daemon" / "tests" / "contracts" / "outcomes.json"
OUT = HERE / "proto" / "triald" / "v1" / "outcomes.proto"

HEADER = '''// SPDX-License-Identifier: AGPL-3.0-or-later
//
// @generated by tools/generate_outcomes_proto.py from the vendored
// outcomes.json. Do not edit: `make check-proto` regenerates this and fails on
// a difference.
//
// The `.tdr` outcome taxonomy, which belongs to the family rather than to this
// daemon (`contracts/INTERACTIONS.md` §6). The authored copy is the JSON; this
// is a view of it that protobuf can read.
//
// The value names carry no enum prefix on purpose: protobuf's JSON mapping puts
// the value name on the wire, and every other copy of this table — every `.tdr`
// file, every analysis script — says `HIT`.

syntax = "proto3";

package triald.v1;

'''


def main() -> int:
    parser = argparse.ArgumentParser(description=__doc__)
    # `--check` answers from memory rather than by writing and then asking git
    # whether anything changed. The git version is vacuous for a file that is
    # not tracked yet, which is exactly when a new generator is least trusted.
    parser.add_argument(
        "--check", action="store_true", help="fail if the file is not what this would write"
    )
    arguments = parser.parse_args()

    taxonomy = json.loads(TAXONOMY.read_text())
    outcomes = taxonomy["outcomes"]

    # proto3 requires the first value to be zero; the taxonomy starts at -1.
    ordered = sorted(outcomes, key=lambda o: (o["value"] != 0, o["value"]))

    lines = [HEADER, "// How a trial ended.\nenum TrialOutcome {\n"]
    for outcome in ordered:
        for sentence in wrapped(outcome["summary"]):
            lines.append(f"  // {sentence}\n")
        lines.append(f'  {outcome["name"]} = {outcome["value"]};\n\n')
    lines.append("}\n")

    text = "".join(lines).replace("\n\n}", "\n}")
    current = OUT.read_text() if OUT.exists() else None

    if current == text:
        print(f"{OUT.relative_to(HERE)} is up to date")
        return 0

    if arguments.check:
        print(f"{OUT.relative_to(HERE)} is not what outcomes.json produces.")
        print("The taxonomy changed and the generated enum did not follow it.")
        print("Run `make proto` and commit the result with the change that caused it.")
        return 1

    OUT.write_text(text)
    print(f"wrote {OUT.relative_to(HERE)}")
    return 0


def wrapped(summary: str, width: int = 74) -> list[str]:
    words, line, out = summary.split(), "", []
    for word in words:
        if line and len(line) + 1 + len(word) > width:
            out.append(line)
            line = word
        else:
            line = f"{line} {word}".strip()
    if line:
        out.append(line)
    return out


if __name__ == "__main__":
    sys.exit(main())
